// Generated by tools/quiz-raquetes.ts on 2026-07-02
// Do NOT edit manually. Re-run: npm run quiz:raquetes
// Single source of truth: same scorer + pipeline as Tury.

import type { ArquetipoSlug } from './quiz-perfil'

export interface QuizRaqueteCard {
  slug:           string
  name:           string
  nome_curto:     string
  marca:          string
  price:          number | null
  image_url:      string | null
  destaques:      Array<{ label: string; v: number }>
  custoBeneficio: boolean
  score:          number
}

export const QUIZ_RAQUETES: Record<ArquetipoSlug, QuizRaqueteCard[]> = 
{
  "muralha": [
    {
      "slug": "vision-pyramid-25",
      "name": "Vision Pyramid 2025",
      "nome_curto": "Pyramid",
      "marca": "Vision",
      "price": 1199,
      "image_url": "/raquetes/vision-pyramid-25.webp",
      "destaques": [
        {
          "label": "Controle",
          "v": 8
        },
        {
          "label": "Conforto",
          "v": 8
        }
      ],
      "custoBeneficio": true,
      "score": 7.1
    },
    {
      "slug": "ceu",
      "name": "CÉU 2024",
      "nome_curto": "CÉU",
      "marca": "Heroe's",
      "price": 1699,
      "image_url": "/raquetes/ceu.webp",
      "destaques": [
        {
          "label": "Conforto",
          "v": 8
        },
        {
          "label": "Controle",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 7
    },
    {
      "slug": "turquoise-tq-fire-azul",
      "name": "Turquoise TQ Fire Azul 2025",
      "nome_curto": "TQ Fire Azul",
      "marca": "Turquoise",
      "price": 2299,
      "image_url": "/raquetes/turquoise-tq-fire-azul.webp",
      "destaques": [
        {
          "label": "Controle",
          "v": 9
        },
        {
          "label": "Manuseio",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 6.8
    },
    {
      "slug": "kona-maddox-guga",
      "name": "Maddox Guga 2024",
      "nome_curto": "Maddox Guga",
      "marca": "Kona",
      "price": 1199,
      "image_url": "/raquetes/kona-maddox-guga.webp",
      "destaques": [
        {
          "label": "Controle",
          "v": 9
        },
        {
          "label": "Conforto",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 6.7
    },
    {
      "slug": "dropshot-renegade-comfort-bt",
      "name": "Renegade Comfort BT 2025",
      "nome_curto": "Renegade Comfort BT",
      "marca": "Drop Shot",
      "price": 799.9,
      "image_url": "/raquetes/dropshot-renegade-comfort-bt.webp",
      "destaques": [
        {
          "label": "Conforto",
          "v": 8
        },
        {
          "label": "Manuseio",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 6.7
    },
    {
      "slug": "mormaii-vitoria-marchezini-ii",
      "name": "Vitória Marchezini II 2024",
      "nome_curto": "Vitória Marchezini II",
      "marca": "Mormaii",
      "price": 2499.9,
      "image_url": "/raquetes/mormaii-vitoria-marchezini-ii.webp",
      "destaques": [
        {
          "label": "Controle",
          "v": 7
        },
        {
          "label": "Conforto",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 6.7
    }
  ],
  "contra-atacante": [
    {
      "slug": "vision-pyramid-25",
      "name": "Vision Pyramid 2025",
      "nome_curto": "Pyramid",
      "marca": "Vision",
      "price": 1199,
      "image_url": "/raquetes/vision-pyramid-25.webp",
      "destaques": [
        {
          "label": "Controle",
          "v": 8
        },
        {
          "label": "Conforto",
          "v": 8
        }
      ],
      "custoBeneficio": true,
      "score": 7.1
    },
    {
      "slug": "ceu",
      "name": "CÉU 2024",
      "nome_curto": "CÉU",
      "marca": "Heroe's",
      "price": 1699,
      "image_url": "/raquetes/ceu.webp",
      "destaques": [
        {
          "label": "Conforto",
          "v": 8
        },
        {
          "label": "Controle",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 7
    },
    {
      "slug": "turquoise-tq-fire-azul",
      "name": "Turquoise TQ Fire Azul 2025",
      "nome_curto": "TQ Fire Azul",
      "marca": "Turquoise",
      "price": 2299,
      "image_url": "/raquetes/turquoise-tq-fire-azul.webp",
      "destaques": [
        {
          "label": "Controle",
          "v": 9
        },
        {
          "label": "Manuseio",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 6.8
    },
    {
      "slug": "kona-maddox-guga",
      "name": "Maddox Guga 2024",
      "nome_curto": "Maddox Guga",
      "marca": "Kona",
      "price": 1199,
      "image_url": "/raquetes/kona-maddox-guga.webp",
      "destaques": [
        {
          "label": "Controle",
          "v": 9
        },
        {
          "label": "Conforto",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 6.7
    },
    {
      "slug": "dropshot-renegade-comfort-bt",
      "name": "Renegade Comfort BT 2025",
      "nome_curto": "Renegade Comfort BT",
      "marca": "Drop Shot",
      "price": 799.9,
      "image_url": "/raquetes/dropshot-renegade-comfort-bt.webp",
      "destaques": [
        {
          "label": "Conforto",
          "v": 8
        },
        {
          "label": "Manuseio",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 6.7
    },
    {
      "slug": "mormaii-vitoria-marchezini-ii",
      "name": "Vitória Marchezini II 2024",
      "nome_curto": "Vitória Marchezini II",
      "marca": "Mormaii",
      "price": 2499.9,
      "image_url": "/raquetes/mormaii-vitoria-marchezini-ii.webp",
      "destaques": [
        {
          "label": "Controle",
          "v": 7
        },
        {
          "label": "Conforto",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 6.7
    }
  ],
  "canhao": [
    {
      "slug": "dropshot-canyon-pro-bt-10-2024",
      "name": "Canyon Pro BT 1.0 2024",
      "nome_curto": "Canyon Pro BT 1.0",
      "marca": "Drop Shot",
      "price": 2540,
      "image_url": "/raquetes/dropshot-canyon-pro-bt-10-2024.webp",
      "destaques": [
        {
          "label": "Potência",
          "v": 7
        },
        {
          "label": "Conforto",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 6.6
    },
    {
      "slug": "poison-bee-2026",
      "name": "Poison Bee 2026",
      "nome_curto": "Poison Bee",
      "marca": "AMA Sport",
      "price": 3100,
      "image_url": "/raquetes/poison-bee-2026.webp",
      "destaques": [
        {
          "label": "Potência",
          "v": 7
        },
        {
          "label": "Conforto",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 6.6
    },
    {
      "slug": "kona-maverick-black-2025",
      "name": "Maverick Black 2025",
      "nome_curto": "Maverick Black",
      "marca": "Kona",
      "price": 2520,
      "image_url": "/raquetes/kona-maverick-black-2025.webp",
      "destaques": [
        {
          "label": "Potência",
          "v": 7
        },
        {
          "label": "Manuseio",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 6.5
    },
    {
      "slug": "zeiq-brave-rafa-miller-2025",
      "name": "Brave Rafa Miller 12k 2025",
      "nome_curto": "Brave Rafa Miller 12k",
      "marca": "Zeiq",
      "price": 1640.27,
      "image_url": "/raquetes/zeiq-brave-rafa-miller-2025.webp",
      "destaques": [
        {
          "label": "Manuseio",
          "v": 7
        },
        {
          "label": "Spin",
          "v": 7
        }
      ],
      "custoBeneficio": true,
      "score": 6.4
    },
    {
      "slug": "fobel-macaw",
      "name": "Macaw 2025",
      "nome_curto": "Macaw",
      "marca": "Fobel",
      "price": 2346,
      "image_url": "/raquetes/fobel-macaw.webp",
      "destaques": [
        {
          "label": "Manuseio",
          "v": 7
        },
        {
          "label": "Estabilidade",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 6.4
    },
    {
      "slug": "flash-2026",
      "name": "Minimalist Flash 2026",
      "nome_curto": "Flash",
      "marca": "Minimalist",
      "price": 2158.23,
      "image_url": "/raquetes/minimalist-flash-2026.webp",
      "destaques": [
        {
          "label": "Manuseio",
          "v": 7
        },
        {
          "label": "Spin",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 6.4
    }
  ],
  "dono-da-rede": [
    {
      "slug": "dropshot-canyon-pro-bt-10-2024",
      "name": "Canyon Pro BT 1.0 2024",
      "nome_curto": "Canyon Pro BT 1.0",
      "marca": "Drop Shot",
      "price": 2540,
      "image_url": "/raquetes/dropshot-canyon-pro-bt-10-2024.webp",
      "destaques": [
        {
          "label": "Potência",
          "v": 7
        },
        {
          "label": "Conforto",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 6.6
    },
    {
      "slug": "poison-bee-2026",
      "name": "Poison Bee 2026",
      "nome_curto": "Poison Bee",
      "marca": "AMA Sport",
      "price": 3100,
      "image_url": "/raquetes/poison-bee-2026.webp",
      "destaques": [
        {
          "label": "Potência",
          "v": 7
        },
        {
          "label": "Conforto",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 6.6
    },
    {
      "slug": "kona-maverick-black-2025",
      "name": "Maverick Black 2025",
      "nome_curto": "Maverick Black",
      "marca": "Kona",
      "price": 2520,
      "image_url": "/raquetes/kona-maverick-black-2025.webp",
      "destaques": [
        {
          "label": "Potência",
          "v": 7
        },
        {
          "label": "Manuseio",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 6.5
    },
    {
      "slug": "zeiq-brave-rafa-miller-2025",
      "name": "Brave Rafa Miller 12k 2025",
      "nome_curto": "Brave Rafa Miller 12k",
      "marca": "Zeiq",
      "price": 1640.27,
      "image_url": "/raquetes/zeiq-brave-rafa-miller-2025.webp",
      "destaques": [
        {
          "label": "Manuseio",
          "v": 7
        },
        {
          "label": "Spin",
          "v": 7
        }
      ],
      "custoBeneficio": true,
      "score": 6.4
    },
    {
      "slug": "fobel-macaw",
      "name": "Macaw 2025",
      "nome_curto": "Macaw",
      "marca": "Fobel",
      "price": 2346,
      "image_url": "/raquetes/fobel-macaw.webp",
      "destaques": [
        {
          "label": "Manuseio",
          "v": 7
        },
        {
          "label": "Estabilidade",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 6.4
    },
    {
      "slug": "flash-2026",
      "name": "Minimalist Flash 2026",
      "nome_curto": "Flash",
      "marca": "Minimalist",
      "price": 2158.23,
      "image_url": "/raquetes/minimalist-flash-2026.webp",
      "destaques": [
        {
          "label": "Manuseio",
          "v": 7
        },
        {
          "label": "Spin",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 6.4
    }
  ],
  "finalizador": [
    {
      "slug": "dropshot-canyon-pro-bt-10-2024",
      "name": "Canyon Pro BT 1.0 2024",
      "nome_curto": "Canyon Pro BT 1.0",
      "marca": "Drop Shot",
      "price": 2540,
      "image_url": "/raquetes/dropshot-canyon-pro-bt-10-2024.webp",
      "destaques": [
        {
          "label": "Potência",
          "v": 7
        },
        {
          "label": "Conforto",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 6.6
    },
    {
      "slug": "poison-bee-2026",
      "name": "Poison Bee 2026",
      "nome_curto": "Poison Bee",
      "marca": "AMA Sport",
      "price": 3100,
      "image_url": "/raquetes/poison-bee-2026.webp",
      "destaques": [
        {
          "label": "Potência",
          "v": 7
        },
        {
          "label": "Conforto",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 6.6
    },
    {
      "slug": "kona-maverick-black-2025",
      "name": "Maverick Black 2025",
      "nome_curto": "Maverick Black",
      "marca": "Kona",
      "price": 2520,
      "image_url": "/raquetes/kona-maverick-black-2025.webp",
      "destaques": [
        {
          "label": "Potência",
          "v": 7
        },
        {
          "label": "Manuseio",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 6.5
    },
    {
      "slug": "zeiq-brave-rafa-miller-2025",
      "name": "Brave Rafa Miller 12k 2025",
      "nome_curto": "Brave Rafa Miller 12k",
      "marca": "Zeiq",
      "price": 1640.27,
      "image_url": "/raquetes/zeiq-brave-rafa-miller-2025.webp",
      "destaques": [
        {
          "label": "Manuseio",
          "v": 7
        },
        {
          "label": "Spin",
          "v": 7
        }
      ],
      "custoBeneficio": true,
      "score": 6.4
    },
    {
      "slug": "fobel-macaw",
      "name": "Macaw 2025",
      "nome_curto": "Macaw",
      "marca": "Fobel",
      "price": 2346,
      "image_url": "/raquetes/fobel-macaw.webp",
      "destaques": [
        {
          "label": "Manuseio",
          "v": 7
        },
        {
          "label": "Estabilidade",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 6.4
    },
    {
      "slug": "flash-2026",
      "name": "Minimalist Flash 2026",
      "nome_curto": "Flash",
      "marca": "Minimalist",
      "price": 2158.23,
      "image_url": "/raquetes/minimalist-flash-2026.webp",
      "destaques": [
        {
          "label": "Manuseio",
          "v": 7
        },
        {
          "label": "Spin",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 6.4
    }
  ],
  "camaleao": [
    {
      "slug": "ceu",
      "name": "CÉU 2024",
      "nome_curto": "CÉU",
      "marca": "Heroe's",
      "price": 1699,
      "image_url": "/raquetes/ceu.webp",
      "destaques": [
        {
          "label": "Conforto",
          "v": 8
        },
        {
          "label": "Controle",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 6.8
    },
    {
      "slug": "vision-pyramid-25",
      "name": "Vision Pyramid 2025",
      "nome_curto": "Pyramid",
      "marca": "Vision",
      "price": 1199,
      "image_url": "/raquetes/vision-pyramid-25.webp",
      "destaques": [
        {
          "label": "Controle",
          "v": 8
        },
        {
          "label": "Conforto",
          "v": 8
        }
      ],
      "custoBeneficio": true,
      "score": 6.8
    },
    {
      "slug": "athena-midnight-26",
      "name": "Athena Midnight 2026",
      "nome_curto": "Athena Midnight",
      "marca": "AMA Sport",
      "price": 3199.99,
      "image_url": "/raquetes/athena-midnight-26.webp",
      "destaques": [
        {
          "label": "Conforto",
          "v": 8
        },
        {
          "label": "Manuseio",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 6.6
    },
    {
      "slug": "mormaii-vitoria-marchezini-ii",
      "name": "Vitória Marchezini II 2024",
      "nome_curto": "Vitória Marchezini II",
      "marca": "Mormaii",
      "price": 2499.9,
      "image_url": "/raquetes/mormaii-vitoria-marchezini-ii.webp",
      "destaques": [
        {
          "label": "Controle",
          "v": 7
        },
        {
          "label": "Conforto",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 6.6
    },
    {
      "slug": "zeiq-brave-rafa-miller-2025",
      "name": "Brave Rafa Miller 12k 2025",
      "nome_curto": "Brave Rafa Miller 12k",
      "marca": "Zeiq",
      "price": 1640.27,
      "image_url": "/raquetes/zeiq-brave-rafa-miller-2025.webp",
      "destaques": [
        {
          "label": "Manuseio",
          "v": 7
        },
        {
          "label": "Spin",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 6.5
    },
    {
      "slug": "dropshot-canyon-pro-bt-10-2024",
      "name": "Canyon Pro BT 1.0 2024",
      "nome_curto": "Canyon Pro BT 1.0",
      "marca": "Drop Shot",
      "price": 2540,
      "image_url": "/raquetes/dropshot-canyon-pro-bt-10-2024.webp",
      "destaques": [
        {
          "label": "Potência",
          "v": 7
        },
        {
          "label": "Conforto",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 6.5
    }
  ]
}
