// Generated by tools/quiz-raquetes.ts on 2026-09-11
// Do NOT edit manually. Re-run: npm run quiz:raquetes
// Single source of truth: same scorer + pipeline as Tury.

import type { ArquetipoSlug } from './quiz-perfil'

export interface QuizRaqueteCard {
  slug:           string
  name:           string
  nome_curto:     string
  marca:          string
  price:          number | null
  image_url:      string | null
  destaques:      Array<{ label: string; v: number }>
  custoBeneficio: boolean
  score:          number
}

export const QUIZ_RAQUETES: Record<ArquetipoSlug, QuizRaqueteCard[]> = 
{
  "muralha": [
    {
      "slug": "ceu",
      "name": "CÉU",
      "nome_curto": "CÉU",
      "marca": "Heroe's",
      "price": 1424.05,
      "image_url": "/raquetes/ceu.webp",
      "destaques": [
        {
          "label": "Conforto",
          "v": 8
        },
        {
          "label": "Controle",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 7
    },
    {
      "slug": "mormaii-vitoria-marchezini-iii",
      "name": "Vitória Marchezini III",
      "nome_curto": "Vitória Marchezini III",
      "marca": "Mormaii",
      "price": 2599,
      "image_url": "/raquetes/mormaii-vitoria-marchezini-iii.webp",
      "destaques": [
        {
          "label": "Controle",
          "v": 7
        },
        {
          "label": "Conforto",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 6.9
    },
    {
      "slug": "z-soft",
      "name": "Z Soft",
      "nome_curto": "Z Soft",
      "marca": "Zand",
      "price": 555.44,
      "image_url": "/raquetes/z-soft.webp",
      "destaques": [
        {
          "label": "Conforto",
          "v": 8
        },
        {
          "label": "Controle",
          "v": 7
        }
      ],
      "custoBeneficio": true,
      "score": 6.9
    },
    {
      "slug": "kona-maddox-guga",
      "name": "Maddox Guga",
      "nome_curto": "Maddox Guga",
      "marca": "Kona",
      "price": 913.26,
      "image_url": "/raquetes/kona-maddox-guga.webp",
      "destaques": [
        {
          "label": "Controle",
          "v": 9
        },
        {
          "label": "Conforto",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 6.7
    },
    {
      "slug": "zeiq-pro-violet-2026",
      "name": "Pro Violet",
      "nome_curto": "Pro Violet 2026 - Douglas Collani",
      "marca": "Zeiq",
      "price": 1799,
      "image_url": "/raquetes/zeiq-pro-violet-2026.webp",
      "destaques": [
        {
          "label": "Controle",
          "v": 8
        },
        {
          "label": "Manuseio",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 6.7
    },
    {
      "slug": "vision-supercarbon-pro-2026",
      "name": "Supercarbon Pro 2026",
      "nome_curto": "Supercarbon Pro",
      "marca": "Vision",
      "price": 1605.19,
      "image_url": "/raquetes/vision-supercarbon-pro-2026.webp",
      "destaques": [
        {
          "label": "Controle",
          "v": 8
        },
        {
          "label": "Conforto",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 6.7
    }
  ],
  "contra-atacante": [
    {
      "slug": "ceu",
      "name": "CÉU",
      "nome_curto": "CÉU",
      "marca": "Heroe's",
      "price": 1424.05,
      "image_url": "/raquetes/ceu.webp",
      "destaques": [
        {
          "label": "Conforto",
          "v": 8
        },
        {
          "label": "Controle",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 7
    },
    {
      "slug": "mormaii-vitoria-marchezini-iii",
      "name": "Vitória Marchezini III",
      "nome_curto": "Vitória Marchezini III",
      "marca": "Mormaii",
      "price": 2599,
      "image_url": "/raquetes/mormaii-vitoria-marchezini-iii.webp",
      "destaques": [
        {
          "label": "Controle",
          "v": 7
        },
        {
          "label": "Conforto",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 6.9
    },
    {
      "slug": "z-soft",
      "name": "Z Soft",
      "nome_curto": "Z Soft",
      "marca": "Zand",
      "price": 555.44,
      "image_url": "/raquetes/z-soft.webp",
      "destaques": [
        {
          "label": "Conforto",
          "v": 8
        },
        {
          "label": "Controle",
          "v": 7
        }
      ],
      "custoBeneficio": true,
      "score": 6.9
    },
    {
      "slug": "kona-maddox-guga",
      "name": "Maddox Guga",
      "nome_curto": "Maddox Guga",
      "marca": "Kona",
      "price": 913.26,
      "image_url": "/raquetes/kona-maddox-guga.webp",
      "destaques": [
        {
          "label": "Controle",
          "v": 9
        },
        {
          "label": "Conforto",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 6.7
    },
    {
      "slug": "zeiq-pro-violet-2026",
      "name": "Pro Violet",
      "nome_curto": "Pro Violet 2026 - Douglas Collani",
      "marca": "Zeiq",
      "price": 1799,
      "image_url": "/raquetes/zeiq-pro-violet-2026.webp",
      "destaques": [
        {
          "label": "Controle",
          "v": 8
        },
        {
          "label": "Manuseio",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 6.7
    },
    {
      "slug": "vision-supercarbon-pro-2026",
      "name": "Supercarbon Pro 2026",
      "nome_curto": "Supercarbon Pro",
      "marca": "Vision",
      "price": 1605.19,
      "image_url": "/raquetes/vision-supercarbon-pro-2026.webp",
      "destaques": [
        {
          "label": "Controle",
          "v": 8
        },
        {
          "label": "Conforto",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 6.7
    }
  ],
  "canhao": [
    {
      "slug": "dropshot-canyon-pro-bt-10-2024",
      "name": "Canyon Pro BT 1.0",
      "nome_curto": "Canyon Pro BT 1.0",
      "marca": "Drop Shot",
      "price": 2540,
      "image_url": "/raquetes/dropshot-canyon-pro-bt-10-2024.webp",
      "destaques": [
        {
          "label": "Potência",
          "v": 7
        },
        {
          "label": "Conforto",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 6.6
    },
    {
      "slug": "poison-bee-2026",
      "name": "Poison Bee 2026",
      "nome_curto": "Poison Bee",
      "marca": "AMA Sport",
      "price": 2500,
      "image_url": "/raquetes/poison-bee-2026.webp",
      "destaques": [
        {
          "label": "Potência",
          "v": 7
        },
        {
          "label": "Conforto",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 6.6
    },
    {
      "slug": "kona-maverick-black-2025",
      "name": "Maverick Black",
      "nome_curto": "Maverick Black",
      "marca": "Kona",
      "price": 1329.05,
      "image_url": "/raquetes/kona-maverick-black-2025.webp",
      "destaques": [
        {
          "label": "Potência",
          "v": 7
        },
        {
          "label": "Manuseio",
          "v": 7
        }
      ],
      "custoBeneficio": true,
      "score": 6.5
    },
    {
      "slug": "zeiq-brave-rafa-miller-2025",
      "name": "Brave Rafa Miller 12k",
      "nome_curto": "Brave Rafa Miller 12k",
      "marca": "Zeiq",
      "price": 1917.13,
      "image_url": "/raquetes/zeiq-brave-rafa-miller-2025.webp",
      "destaques": [
        {
          "label": "Manuseio",
          "v": 7
        },
        {
          "label": "Spin",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 6.4
    },
    {
      "slug": "fobel-macaw-2025",
      "name": "Macaw 2025",
      "nome_curto": "Macaw",
      "marca": "Fobel",
      "price": 2399.9,
      "image_url": "/raquetes/fobel-macaw-2025.webp",
      "destaques": [
        {
          "label": "Manuseio",
          "v": 7
        },
        {
          "label": "Spin",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 6.4
    },
    {
      "slug": "flash-2026",
      "name": "Flash 2026",
      "nome_curto": "Flash",
      "marca": "Minimalist",
      "price": 2279.05,
      "image_url": "/raquetes/minimalist-flash-2026.webp",
      "destaques": [
        {
          "label": "Manuseio",
          "v": 7
        },
        {
          "label": "Spin",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 6.4
    }
  ],
  "dono-da-rede": [
    {
      "slug": "dropshot-canyon-pro-bt-10-2024",
      "name": "Canyon Pro BT 1.0",
      "nome_curto": "Canyon Pro BT 1.0",
      "marca": "Drop Shot",
      "price": 2540,
      "image_url": "/raquetes/dropshot-canyon-pro-bt-10-2024.webp",
      "destaques": [
        {
          "label": "Potência",
          "v": 7
        },
        {
          "label": "Conforto",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 6.6
    },
    {
      "slug": "poison-bee-2026",
      "name": "Poison Bee 2026",
      "nome_curto": "Poison Bee",
      "marca": "AMA Sport",
      "price": 2500,
      "image_url": "/raquetes/poison-bee-2026.webp",
      "destaques": [
        {
          "label": "Potência",
          "v": 7
        },
        {
          "label": "Conforto",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 6.6
    },
    {
      "slug": "kona-maverick-black-2025",
      "name": "Maverick Black",
      "nome_curto": "Maverick Black",
      "marca": "Kona",
      "price": 1329.05,
      "image_url": "/raquetes/kona-maverick-black-2025.webp",
      "destaques": [
        {
          "label": "Potência",
          "v": 7
        },
        {
          "label": "Manuseio",
          "v": 7
        }
      ],
      "custoBeneficio": true,
      "score": 6.5
    },
    {
      "slug": "zeiq-brave-rafa-miller-2025",
      "name": "Brave Rafa Miller 12k",
      "nome_curto": "Brave Rafa Miller 12k",
      "marca": "Zeiq",
      "price": 1917.13,
      "image_url": "/raquetes/zeiq-brave-rafa-miller-2025.webp",
      "destaques": [
        {
          "label": "Manuseio",
          "v": 7
        },
        {
          "label": "Spin",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 6.4
    },
    {
      "slug": "fobel-macaw-2025",
      "name": "Macaw 2025",
      "nome_curto": "Macaw",
      "marca": "Fobel",
      "price": 2399.9,
      "image_url": "/raquetes/fobel-macaw-2025.webp",
      "destaques": [
        {
          "label": "Manuseio",
          "v": 7
        },
        {
          "label": "Spin",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 6.4
    },
    {
      "slug": "flash-2026",
      "name": "Flash 2026",
      "nome_curto": "Flash",
      "marca": "Minimalist",
      "price": 2279.05,
      "image_url": "/raquetes/minimalist-flash-2026.webp",
      "destaques": [
        {
          "label": "Manuseio",
          "v": 7
        },
        {
          "label": "Spin",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 6.4
    }
  ],
  "finalizador": [
    {
      "slug": "dropshot-canyon-pro-bt-10-2024",
      "name": "Canyon Pro BT 1.0",
      "nome_curto": "Canyon Pro BT 1.0",
      "marca": "Drop Shot",
      "price": 2540,
      "image_url": "/raquetes/dropshot-canyon-pro-bt-10-2024.webp",
      "destaques": [
        {
          "label": "Potência",
          "v": 7
        },
        {
          "label": "Conforto",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 6.6
    },
    {
      "slug": "poison-bee-2026",
      "name": "Poison Bee 2026",
      "nome_curto": "Poison Bee",
      "marca": "AMA Sport",
      "price": 2500,
      "image_url": "/raquetes/poison-bee-2026.webp",
      "destaques": [
        {
          "label": "Potência",
          "v": 7
        },
        {
          "label": "Conforto",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 6.6
    },
    {
      "slug": "kona-maverick-black-2025",
      "name": "Maverick Black",
      "nome_curto": "Maverick Black",
      "marca": "Kona",
      "price": 1329.05,
      "image_url": "/raquetes/kona-maverick-black-2025.webp",
      "destaques": [
        {
          "label": "Potência",
          "v": 7
        },
        {
          "label": "Manuseio",
          "v": 7
        }
      ],
      "custoBeneficio": true,
      "score": 6.5
    },
    {
      "slug": "zeiq-brave-rafa-miller-2025",
      "name": "Brave Rafa Miller 12k",
      "nome_curto": "Brave Rafa Miller 12k",
      "marca": "Zeiq",
      "price": 1917.13,
      "image_url": "/raquetes/zeiq-brave-rafa-miller-2025.webp",
      "destaques": [
        {
          "label": "Manuseio",
          "v": 7
        },
        {
          "label": "Spin",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 6.4
    },
    {
      "slug": "fobel-macaw-2025",
      "name": "Macaw 2025",
      "nome_curto": "Macaw",
      "marca": "Fobel",
      "price": 2399.9,
      "image_url": "/raquetes/fobel-macaw-2025.webp",
      "destaques": [
        {
          "label": "Manuseio",
          "v": 7
        },
        {
          "label": "Spin",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 6.4
    },
    {
      "slug": "flash-2026",
      "name": "Flash 2026",
      "nome_curto": "Flash",
      "marca": "Minimalist",
      "price": 2279.05,
      "image_url": "/raquetes/minimalist-flash-2026.webp",
      "destaques": [
        {
          "label": "Manuseio",
          "v": 7
        },
        {
          "label": "Spin",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 6.4
    }
  ],
  "camaleao": [
    {
      "slug": "ceu",
      "name": "CÉU",
      "nome_curto": "CÉU",
      "marca": "Heroe's",
      "price": 1424.05,
      "image_url": "/raquetes/ceu.webp",
      "destaques": [
        {
          "label": "Conforto",
          "v": 8
        },
        {
          "label": "Controle",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 6.8
    },
    {
      "slug": "mormaii-vitoria-marchezini-iii",
      "name": "Vitória Marchezini III",
      "nome_curto": "Vitória Marchezini III",
      "marca": "Mormaii",
      "price": 2599,
      "image_url": "/raquetes/mormaii-vitoria-marchezini-iii.webp",
      "destaques": [
        {
          "label": "Controle",
          "v": 7
        },
        {
          "label": "Conforto",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 6.7
    },
    {
      "slug": "z-soft",
      "name": "Z Soft",
      "nome_curto": "Z Soft",
      "marca": "Zand",
      "price": 555.44,
      "image_url": "/raquetes/z-soft.webp",
      "destaques": [
        {
          "label": "Conforto",
          "v": 8
        },
        {
          "label": "Controle",
          "v": 7
        }
      ],
      "custoBeneficio": true,
      "score": 6.7
    },
    {
      "slug": "athena-boreal-26",
      "name": "Athena Boreal",
      "nome_curto": "Athena Boreal",
      "marca": "AMA Sport",
      "price": 2885.67,
      "image_url": "/raquetes/athena-boreal-26.webp",
      "destaques": [
        {
          "label": "Conforto",
          "v": 8
        },
        {
          "label": "Manuseio",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 6.6
    },
    {
      "slug": "vision-gold-carbon-titanium-2025",
      "name": "Gold Carbon Titanium 2025",
      "nome_curto": "Gold Carbon Titanium",
      "marca": "Vision",
      "price": 1499,
      "image_url": "/raquetes/vision-gold-carbon-titanium-2025.webp",
      "destaques": [
        {
          "label": "Controle",
          "v": 7
        },
        {
          "label": "Conforto",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 6.6
    },
    {
      "slug": "zeiq-brave-rafa-miller-2025",
      "name": "Brave Rafa Miller 12k",
      "nome_curto": "Brave Rafa Miller 12k",
      "marca": "Zeiq",
      "price": 1917.13,
      "image_url": "/raquetes/zeiq-brave-rafa-miller-2025.webp",
      "destaques": [
        {
          "label": "Manuseio",
          "v": 7
        },
        {
          "label": "Spin",
          "v": 7
        }
      ],
      "custoBeneficio": false,
      "score": 6.5
    }
  ]
}
