// Generated by tools/quiz-raquetes.ts on 2026-07-02
// Do NOT edit manually. Re-run: npm run quiz:raquetes
// Single source of truth: same scorer + pipeline as Tury.

import type { ArquetipoSlug } from './quiz-perfil'

export interface QuizRaqueteCard {
  slug:           string
  name:           string
  nome_curto:     string
  marca:          string
  price:          number | null
  image_url:      string | null
  destaques:      Array<{ label: string; v: number }>
  custoBeneficio: boolean
  score:          number
}

export const QUIZ_RAQUETES: Record<ArquetipoSlug, QuizRaqueteCard[]> =
{
  "muralha": [
    {
      "slug": "vision-pyramid-25",
      "name": "Vision Pyramid 2025",
      "nome_curto": "Pyramid",
      "marca": "Vision",
      "price": 1199,
      "image_url": "/raquetes/vision-pyramid-25.webp",
      "destaques": [
        { "label": "Controle", "v": 8 },
        { "label": "Conforto", "v": 8 }
      ],
      "custoBeneficio": false,
      "score": 7.1
    },
    {
      "slug": "ceu",
      "name": "CÉU 2024",
      "nome_curto": "CÉU",
      "marca": "Heroe's",
      "price": 1699,
      "image_url": "/raquetes/ceu.webp",
      "destaques": [
        { "label": "Conforto", "v": 8 },
        { "label": "Controle", "v": 7 }
      ],
      "custoBeneficio": false,
      "score": 7
    },
    {
      "slug": "forest",
      "name": "Forest 2025",
      "nome_curto": "Forest",
      "marca": "Heroe's",
      "price": 969.3,
      "image_url": "/raquetes/forest.webp",
      "destaques": [
        { "label": "Controle", "v": 9 },
        { "label": "Manuseio", "v": 8 }
      ],
      "custoBeneficio": true,
      "score": 6.9
    }
  ],
  "contra-atacante": [
    {
      "slug": "vision-pyramid-25",
      "name": "Vision Pyramid 2025",
      "nome_curto": "Pyramid",
      "marca": "Vision",
      "price": 1199,
      "image_url": "/raquetes/vision-pyramid-25.webp",
      "destaques": [
        { "label": "Controle", "v": 8 },
        { "label": "Conforto", "v": 8 }
      ],
      "custoBeneficio": false,
      "score": 7.1
    },
    {
      "slug": "ceu",
      "name": "CÉU 2024",
      "nome_curto": "CÉU",
      "marca": "Heroe's",
      "price": 1699,
      "image_url": "/raquetes/ceu.webp",
      "destaques": [
        { "label": "Conforto", "v": 8 },
        { "label": "Controle", "v": 7 }
      ],
      "custoBeneficio": false,
      "score": 7
    },
    {
      "slug": "forest",
      "name": "Forest 2025",
      "nome_curto": "Forest",
      "marca": "Heroe's",
      "price": 969.3,
      "image_url": "/raquetes/forest.webp",
      "destaques": [
        { "label": "Controle", "v": 9 },
        { "label": "Manuseio", "v": 8 }
      ],
      "custoBeneficio": true,
      "score": 6.9
    }
  ],
  "canhao": [
    {
      "slug": "dropshot-canyon-pro-bt-10-2024",
      "name": "Canyon Pro BT 1.0 2024",
      "nome_curto": "Canyon Pro BT 1.0",
      "marca": "Drop Shot",
      "price": 2540,
      "image_url": "/raquetes/dropshot-canyon-pro-bt-10-2024.webp",
      "destaques": [
        { "label": "Potência", "v": 7 },
        { "label": "Conforto", "v": 7 }
      ],
      "custoBeneficio": true,
      "score": 6.6
    },
    {
      "slug": "poison-bee-2026",
      "name": "Poison Bee 2026",
      "nome_curto": "Poison Bee",
      "marca": "AMA Sport",
      "price": 3100,
      "image_url": "/raquetes/poison-bee-2026.webp",
      "destaques": [
        { "label": "Potência", "v": 7 },
        { "label": "Conforto", "v": 7 }
      ],
      "custoBeneficio": false,
      "score": 6.6
    },
    {
      "slug": "dropshot-axion-attack-20-2026",
      "name": "Axion Attack 2.0 BT 2026",
      "nome_curto": "Axion Attack 2.0 BT",
      "marca": "Drop Shot",
      "price": 2599.9,
      "image_url": "/raquetes/dropshot-axion-attack-20.webp",
      "destaques": [
        { "label": "Potência", "v": 7 },
        { "label": "Manuseio", "v": 7 }
      ],
      "custoBeneficio": false,
      "score": 6.5
    }
  ],
  "dono-da-rede": [
    {
      "slug": "dropshot-canyon-pro-bt-10-2024",
      "name": "Canyon Pro BT 1.0 2024",
      "nome_curto": "Canyon Pro BT 1.0",
      "marca": "Drop Shot",
      "price": 2540,
      "image_url": "/raquetes/dropshot-canyon-pro-bt-10-2024.webp",
      "destaques": [
        { "label": "Potência", "v": 7 },
        { "label": "Conforto", "v": 7 }
      ],
      "custoBeneficio": true,
      "score": 6.6
    },
    {
      "slug": "poison-bee-2026",
      "name": "Poison Bee 2026",
      "nome_curto": "Poison Bee",
      "marca": "AMA Sport",
      "price": 3100,
      "image_url": "/raquetes/poison-bee-2026.webp",
      "destaques": [
        { "label": "Potência", "v": 7 },
        { "label": "Conforto", "v": 7 }
      ],
      "custoBeneficio": false,
      "score": 6.6
    },
    {
      "slug": "dropshot-axion-attack-20-2026",
      "name": "Axion Attack 2.0 BT 2026",
      "nome_curto": "Axion Attack 2.0 BT",
      "marca": "Drop Shot",
      "price": 2599.9,
      "image_url": "/raquetes/dropshot-axion-attack-20.webp",
      "destaques": [
        { "label": "Potência", "v": 7 },
        { "label": "Manuseio", "v": 7 }
      ],
      "custoBeneficio": false,
      "score": 6.5
    }
  ],
  "finalizador": [
    {
      "slug": "dropshot-canyon-pro-bt-10-2024",
      "name": "Canyon Pro BT 1.0 2024",
      "nome_curto": "Canyon Pro BT 1.0",
      "marca": "Drop Shot",
      "price": 2540,
      "image_url": "/raquetes/dropshot-canyon-pro-bt-10-2024.webp",
      "destaques": [
        { "label": "Potência", "v": 7 },
        { "label": "Conforto", "v": 7 }
      ],
      "custoBeneficio": true,
      "score": 6.6
    },
    {
      "slug": "poison-bee-2026",
      "name": "Poison Bee 2026",
      "nome_curto": "Poison Bee",
      "marca": "AMA Sport",
      "price": 3100,
      "image_url": "/raquetes/poison-bee-2026.webp",
      "destaques": [
        { "label": "Potência", "v": 7 },
        { "label": "Conforto", "v": 7 }
      ],
      "custoBeneficio": false,
      "score": 6.6
    },
    {
      "slug": "dropshot-axion-attack-20-2026",
      "name": "Axion Attack 2.0 BT 2026",
      "nome_curto": "Axion Attack 2.0 BT",
      "marca": "Drop Shot",
      "price": 2599.9,
      "image_url": "/raquetes/dropshot-axion-attack-20.webp",
      "destaques": [
        { "label": "Potência", "v": 7 },
        { "label": "Manuseio", "v": 7 }
      ],
      "custoBeneficio": false,
      "score": 6.5
    }
  ],
  "camaleao": [
    {
      "slug": "ceu",
      "name": "CÉU 2024",
      "nome_curto": "CÉU",
      "marca": "Heroe's",
      "price": 1699,
      "image_url": "/raquetes/ceu.webp",
      "destaques": [
        { "label": "Conforto", "v": 8 },
        { "label": "Controle", "v": 7 }
      ],
      "custoBeneficio": false,
      "score": 6.8
    },
    {
      "slug": "vision-pyramid-25",
      "name": "Vision Pyramid 2025",
      "nome_curto": "Pyramid",
      "marca": "Vision",
      "price": 1199,
      "image_url": "/raquetes/vision-pyramid-25.webp",
      "destaques": [
        { "label": "Controle", "v": 8 },
        { "label": "Conforto", "v": 8 }
      ],
      "custoBeneficio": true,
      "score": 6.8
    },
    {
      "slug": "athena-midnight-26",
      "name": "Athena Midnight 2026",
      "nome_curto": "Athena Midnight",
      "marca": "AMA Sport",
      "price": 3199.99,
      "image_url": "/raquetes/athena-midnight-26.webp",
      "destaques": [
        { "label": "Conforto", "v": 8 },
        { "label": "Manuseio", "v": 7 }
      ],
      "custoBeneficio": false,
      "score": 6.6
    }
  ]
}
